name: Update prebuilt blobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "Galaxy A17 5G (a17xxx)"
            device: "a17xxx"
            firmware: "SM-A176B/INS/350042791234568"
          - module: "Galaxy A54 5G (a54xnsxx)"
            device: "a54xnsxx"
            firmware: "SM-A546E/EGY/350090711234564"
          - module: "Galaxy A56 5G (a56xnaxx)"
            device: "a56xnaxx"
            firmware: "SM-A566B/EUX/352371191234565"
          - module: "Galaxy A73 5G (a73xqxx)"
            device: "a73xqxx"
            firmware: "SM-A736B/XME/352828291234563"
          - module: "Galaxy S22 Ultra (Snapdragon) (b0qxxx)"
            device: "b0qxxx"
            firmware: "SM-S908E/INS/350280381234560"
          - module: "Galaxy S22 Ultra (Exynos) (b0sxxx)"
            device: "b0sxxx"
            firmware: "SM-S908B/EUX/353074281234565"
          - module: "Galaxy Z Flip4 (b4qxxx)"
            device: "b4qxxx"
            firmware: "SM-F721B/EUX/350525851234569"
          - module: "Galaxy S23 (dm1qxxx)"
            device: "dm1qxxx"
            firmware: "SM-S911B/EUX/352404911234563"
          - module: "Galaxy S25+ (pa2qxxx)"
            device: "pa2qxxx"
            firmware: "SM-S936B/EUX/350634601234562"
          - module: "Galaxy S21 FE 5G (Snapdragon) (r9qxxx)"
            device: "r9qxxx"
            firmware: "SM-G990B/EUX/353718681234563"
          - module: "Galaxy S21 FE 5G (Exynos) (r9sxxx)"
            device: "r9sxxx"
            firmware: "SM-G990E/INS/352755851234560"
          - module: "Galaxy S23 FE (r11sxxx)"
            device: "r11sxxx"
            firmware: "SM-S711B/EUX/358615311234564"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            7zip attr ccache clang ffmpeg \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build dependencies
        run: |
          source ./buildenv.sh a52sxq
          ./scripts/build_dependencies.sh

      - name: Update prebuilt blobs
        run: |
          source ./buildenv.sh a52sxq
          ./scripts/internal/update_prebuilt_blobs.sh "${{ matrix.device }}" "${{ matrix.firmware }}"
          echo "PDA_BUILD=$(cat "./prebuilts/samsung/${{ matrix.device }}/.current" | cut -d "/" -f "1")" >> "$GITHUB_ENV"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            prebuilts/samsung/${{ matrix.device }}
          commit-message: 'prebuilts/samsung/${{ matrix.device }}: update blobs to ${{ env.PDA_BUILD }}'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: 'prebuilts/samsung/${{ matrix.device }}'
          delete-branch: true
          title: 'Update prebuilts/samsung/${{ matrix.device }} blobs to ${{ env.PDA_BUILD }}'
          body: ''
